name: Build

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - 'master'
    - 'develop'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      working-directory: Solutions
      run: dotnet restore
    - name: Build
      working-directory: Solutions
      run: dotnet build --no-restore
    - name: Test
      working-directory: Solutions
      run: dotnet test --no-build --verbosity normal